<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class task extends Model
{
    protected $guarded=[];
    protected $touches=['project'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($task){
            Activity::create([
               'project_id'=>$task->project->id,
                'desc'=>'task created'
            ]);
        });


        static::updated(function($task){
            if(!$task->completed){
                return;
            }
            Activity::create([
                'project_id'=>$task->project->id,
                'desc'=>'task completed'
            ]);
        });
    }
    public function complete(){
        $this->update([
            'completed'=>now()
        ]);
    }

    public function incomplete(){
        $this->update([
            'completed'=> null
        ]);
    }

    public function project(){
        return $this->belongsTo(Project::class);
    }

    public function path(){
        return $this->project->path().'/tasks/'.$this->id;
    }

}
